name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+1
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  supabase_flutter: ^1.10.17
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
